### ISSUE TITLE
ピッザより、ワインが良いかと。。。！

### ISSUE THREAD

**Issue by jinmayamashita** [gw-saturday-github/gw-test#1]
## そっちのほうがいいんじゃない？
なぜなら、

- 白ワインの殺菌効果には定評があり、サルモネラ菌、大腸菌などの食中毒菌に対して抗菌力がある
- 赤ワインの渋みと色の成分で、ぶどうの皮に含まれているポリフェノールは抗酸化作用のある物質として、体中の細胞を酸化させて老化を促進する「活性酸素」の働きを抑制・除去し、体を若々しく保ってくれる

**Comment by limgoowa** [comment]
わかりました。修正しときますね。

**Comment by limgoowa** [comment]
修正しましたので、このイシューは閉じときます。
